# -*- coding: utf-8 -*-
"""trained.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziD9orX19zHQA9538J5COOBw7k-3bncp
"""

import numpy as np
import pandas as pd
import torch
import torch.optim as optim
import torch.nn as nn
from torch.utils.data import DataLoader,Dataset,random_split,Subset
from torchvision import transforms
from torchvision.models import mobilenet_v2
from torchvision.datasets import ImageFolder

from google.colab import drive
drive.mount('/content/drive')

device = ('cuda' if torch.cuda.is_available() else 'cpu')

# TRANSFORMS
train_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])
test_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])
# DATASET
train_full_data = ImageFolder('/content/drive/MyDrive/colab notebooks/datasets/PetImages',
                   transform=train_transform)
test_full_data = ImageFolder('/content/drive/MyDrive/colab notebooks/datasets/PetImages',
                   transform=test_transform)

train_size = int(0.8*len(train_full_data))
test_size = len(train_full_data)-train_size
# train_set,_ = random_split(train_full_data, [train_size, test_size])
# _,test_set = random_split(test_full_data, [train_size, test_size])
# train_set, test_set = Subset(train_set, range(10000)), Subset(test_set, range(2000))
indices = torch.randperm(len(train_full_data))
train_indices = indices[:train_size]
test_indices = indices[train_size:]
# train_set = train_full_data[train_indices]
# test_set = test_full_data[test_indices]
train_set = Subset(train_full_data,train_indices)
train_set = Subset(train_set,range(8000))
test_set = Subset(test_full_data,test_indices)
test_set = Subset(test_set,range(2000))
train_loader = DataLoader(train_set, batch_size=32, shuffle=True, pin_memory=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=32, shuffle=False, pin_memory=True, num_workers=2)

# MODEL
model = mobilenet_v2(weights="DEFAULT")

# freeze feature extractor
for param in model.features.parameters():
    param.requires_grad = False

# replace classifier
model.classifier = nn.Sequential(
    nn.Dropout(0.2),
    nn.Linear(1280, 512),
    nn.ReLU(inplace=True),
    nn.Dropout(0.5),
    nn.Linear(512, 2)
)

# move model to gpu
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.classifier.parameters(), lr=0.0003)

# TRAINING
epochs = 10
model.train()

for epoch in range(epochs):
    total_loss = 0
    for features, labels in train_loader:
        features, labels = features.to(device), labels.to(device)

        output = model(features)

        loss = criterion(output, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader)}")

# TESTING
model.eval()
test_loss = 0

with torch.no_grad():
    for features, labels in test_loader:
        features, labels = features.to(device), labels.to(device)
        output = model(features)
        loss = criterion(output, labels)
        test_loss += loss.item()

print(f"Test Loss: {test_loss/len(test_loader)}")

torch.save(model.state_dict(), "/content/drive/MyDrive/mobilenetv2_model.pth")